[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
codecracy = "j8RWHX7RcLfWxkimpbgrSv6cPjUdpdGvjj3n3ikd53S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
